/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118763-g154c00514d-20250313"
#endif /* AVUTIL_FFVERSION_H */
